### ISSUE TITLE
Imap and bellsouth Imap settings

### ISSUE THREAD

**Issue by FebyKris** [SUP3RIA/Atlantr#1]
Hi, first of all I would like to thank you for your  great work! But I think I found some problem when I try with  bellsouth and att.net with valid password...

**Comment by SUP3RIA** [comment]
Sorry for the late response, could you specify your problems in detail?

**Comment by FebyKris** [comment]
Sure, I try put my Bellsouth and att.net email and password in mail_pass.txt and i try run atr...
and then nothing hapen, nothing valid...
but I guess i find solutions,
just change imap addres in hoster.txt
```
bellsouth.net:imap.mail.yahoo.com:993
att.net:imap.mail.yahoo.com:993
```
