### ISSUE TITLE
Please suggest features for next version

### ISSUE THREAD

**Issue by SUP3RIA** [SUP3RIA/Atlantr#11]
Please suggest features for next version

**Comment by Sylo44** [comment]
I would this tool to develop beyond a checker.
How about adding a search feature, where I can search the inbox for specific words in the subject line or search the inbox for specific senders like for example i want to look in my list if anybody has an email in the inbox from @aol.com for example.

**Comment by bl3nd0** [comment]
make it support poth SMTP / IMAP checkers

**Comment by spankders** [comment]
- maybe support imap/smtp
- also a feature to search in the source of the emails will be nice
- nice easy to use gui version
- or another version in GO language

**Comment by SUP3RIA** [comment]
Thanks. I am planning to release a rewrite in Go with the suggested features.
