### ISSUE TITLE
Cannon Checking 

### ISSUE THREAD

**Issue by rzen98** [SUP3RIA/Atlantr#12]
Why i cant check .  Im install gevent and tqdm but thats automatic close (Windows) what line i must fix ? I set thread to 100 but thats same not fixed

**Comment by rzen98** [comment]
I hope next update support for windows :)

**Comment by rzen98** [comment]
Or next update fiture --proxy_list.txt ithink thats good idea

**Comment by rzen98** [comment]
[INFO]Time elapsed: 3.874 seconds.
[INFO] Done.

**Comment by Badro0** [comment]
It works on windows, you just need to install the requirements.
