### ISSUE TITLE
How matches works?

### ISSUE THREAD

**Issue by sydhe** [SUP3RIA/Atlantr#14]
how -g matches.dat works?
I try to use template like in attached file, but it doesn't works:
Example:
[GitHub]|(FROM "github.com")|github.com
I try to use just headline [GitHub] or just domain github.com without | - it doesn't works.

What is wrong? How to create grabbing template?

**Comment by SUP3RIA** [comment]
search|(FROM "domain.com")|discriptor

See https://php.net/manual/en/function.imap-search.php for which criteria can be used.
discriptor is a internal label.
