### ISSUE TITLE
when check unmatched 

### ISSUE THREAD

**Issue by bl3nd0** [SUP3RIA/Atlantr#15]
when check the unmatched list which port by default does it check it?
is it 995?
if so how to make it check for SMTP's Ports like : 25 , 587

also what if i want to make the same on the matched list?

**Comment by SUP3RIA** [comment]
It just checks for port 993 but if you need more sophisticated methods I am happy to implement them.

**Comment by chasingdreamm** [comment]
@bl3nd0 

Can I have ur email address?

**Comment by SUP3RIA** [comment]
You can leave yours here and I will contact you.
