### ISSUE TITLE
Fix some code

### ISSUE THREAD

**Issue by iillegally** [SUP3RIA/Atlantr#19]
You have done a good job with it :+1: 
The speed is great.
Here are some things you need to keep in mind:
Fix the shutdown, it won't shutdown or takes forever.
Sometimes is stucks in middle of checking, can't seem to find the cause of it.
Overall the code needs a clean up, need a recoding in a better way, find a better way to work around with workers and gevent :)

**Comment by SUP3RIA** [comment]
Thanks for the feedback. I know the code has issues but I am not going to work on this as I am going to recode in Go.
