### ISSUE TITLE
Is it possible?

### ISSUE THREAD

**Issue by fantasy2025** [SUP3RIA/Atlantr#20]
Hi Sup3ria,

Thanks for spending time to implement this great tool. I know next to nothing about codes. I'd like to get a clarification from you about how this tool works with unknown domains? the ones we don't know and it's not found in hoster.dat 

Will the tool only check for like imap.domain.com? is it possible to implement more codes so this tool will check for mail portal like mail.domain.com, webmail.domain.com, domain.com/webmail, or wm.domain.com, wmail.domain.com, something like that? by going through possible port like 80, 443... etc?

I know nothing about coding, so I just ask base on what I am thinking. If this is possible, it would work alot better. Because I noticed now, the tool skip so many domains.

Or if anyone knows there is such tool already. please comment and let me know too,

Again thanks a lot !

**Comment by SUP3RIA** [comment]
If there is no setting in the machters.dat a function checks for subdomains defined in this function:
https://github.com/SUP3RIA/Atlantr/blob/master/3.0/atr3.py#L168

The following are checked:
```
sub = [
            'imap',
            'mail',
            'pop',
            'pop3',
            'imap-mail',
            'inbound',
            'mx',
            'imaps',
            'smtp',
            'm']

```
In case you want to extend the list just edit the array for example it could like this:
```

sub = [
            'imap',
            'mail',
            'pop',
            'pop3',
            'imap-mail',
            'inbound',
            'mx',
            'imaps',
            'smtp',
            'm', 
            'example', 
            'example2', 
       
             ]
```
