### ISSUE TITLE
Please help me, tool don't working

### ISSUE THREAD

**Issue by hoangitnet** [SUP3RIA/Atlantr#4]
i try use it but Atlantr Imap Checker have problem
i check mail live and then use Atlantr Imap Checker check again. But Atlantr Imap Checker  message is invalid.
Please help me ! Thank you so much !

**Comment by x080x** [comment]
if can do something
XXX@mtmail.mtsu.edu:XXX
is a outlook.com
no see ur cheker, but exist!
maybe dont know it is a outlook, and more domain, is a BUG, or?
thanks.

**Comment by SUP3RIA** [comment]
Note that some providers are blocking Imap connections, also you can add settings for domains to hosts.dat.
