### ISSUE TITLE
proxy

### ISSUE THREAD

**Issue by lynther** [SUP3RIA/Atlantr#7]
please add proxy to software!!!

**Comment by SUP3RIA** [comment]
Does proxychains not work for you?

**Comment by swordfi5h** [comment]
SUP3RIA can i have your contact? have some small job for u.

**Comment by SUP3RIA** [comment]
Sure. Leave your email address here and I will contact you

**Comment by swordfi5h** [comment]
404@planet.nl

**Comment by chasingdreamm** [comment]
Can you please contact me too SUP3RIA?

chasingdreamm@protonmail.com

**Comment by SUP3RIA** [comment]
I contacted you.
